name: microbial_source_tracking
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  firebase_auth: ^4.17.3
  firebase_core: ^2.25.3
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.13
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7 # this enables accessing local storage 
  file_picker: ^6.1.1 # this too but for files not just images 
  firebase_storage: ^11.6.7


  flutter_gen: any
  cloud_firestore: ^4.15.6
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  flutter_native_splash: ^2.3.10

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/full_glwa_logo.png

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
